server:
  port: 7001

spring:
  application:
    name: finance-eureka
eureka:
  instance:
    hostname: eureka1.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka2.com:7002/eureka